### ISSUE TITLE
- [ ] Realizar Prototipo baja o mediana fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_sa_ppi2020#10]

**Comment by cristianv1211** [comment]
Profe ya quedaron asignadas todas las tareas!!

**Comment by juagui0105** [comment]
![Diapositiva1](https://user-images.githubusercontent.com/66382492/89193389-86eb3580-d56b-11ea-9302-9608d5457f3a.PNG)
![Diapositiva1](https://user-images.githubusercontent.com/66382492/89193404-8ce11680-d56b-11ea-96f8-3d58848050e9.PNG)
![Diapositiva1](https://user-images.githubusercontent.com/66382492/89193424-92d6f780-d56b-11ea-8890-85d8024ecf1a.PNG)
