### ISSUE TITLE
- [ ] Implementación en el Frontend haciendo uso de ReactJS evidenciando la navegación de acuerdo con los prototipos de alta fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_sa_ppi2020#15]

**Comment by JohnFlorez25** [comment]
@valensalazar03 @juagui0105 @paulara04 para dentro 8 días deben evidenciar avances en esta actividad donde tengan las interfaces en REACTJS de lo que se validó en el prototipo en alta fidelidad y recomendaciones de los jurados en la socialización.
El código debe estar en el repositorio del proyecto (o sea este repositorio) validar con la profesora @jennymontoya1001  para que les ayuden a realizar este proceso , les dejo un ejemplo de lo que se debe ir evidenciando.

**Comment by valensalazar03** [comment]
@JohnFlorez25 adjunto links de código y pantallas evidenciando la navegabilidad de la aplicación.

**Comment by cristianv1211** [comment]
@JohnFlorez25 Listo quedo el video en la Wiki, Video subido con exito
