### ISSUE TITLE
- [ ] Definir los servicios del Backend que se deben implementar de acuerdo con las reglas de negocio. (Objeto JSON)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_sa_ppi2020#17]

**Comment by JohnFlorez25** [comment]
@juagui0105 @paulara04 @cristianv1211 El siguiente formato se especifica la estructura de como deben evidenciar cada uno de los servicios backend que van a ser consumidos desde el frontend

[Formato Definición de los servicios backend.docx](https://github.com/JohnFlorez25/equipo1_sa_ppi2020/files/5270555/Formato.Definicion.de.los.servicios.backend.docx)

**Comment by juagui0105** [comment]
@JohnFlorez25 definiciones de Backend ya esta montada en la Wiki
