### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_sa_ppi2020#2]

**Comment by JohnFlorez25** [comment]
@paulara04  Al observar el diagrama de espina de pescado, dejar como problema "mal reciclaje" es muy general para lo que se quiere abordar a nivel del proyecto, es importante que este sea más específico, por ejemplo relacionado a los malos hábitos o poca formación y/o conocimiento que tenemos al poner en práctica y  que sea parte de nuestra vida reciclar, miren que en cada uno de los efectos que han planteado esto conlleva a saber afrontar el problema

**Comment by paulara04** [comment]
@JohnFlorez25 La problemática ya fue corregida, de "mal reciclaje" a "no reciclar.

**Comment by JohnFlorez25** [comment]
@paulara04 el diagrama cumple con lo solicitado pero el problema debemos dejarlo como "Las personas no poseen buenos hábitos para reciclar"
