### ISSUE TITLE
Validar con 5 usuarios la viabilidad del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_sa_ppi2020#6]

**Comment by juagui0105** [comment]
[validaciones equipó 1.docx](https://github.com/JohnFlorez25/equipo1_sa_ppi2020/files/4789405/validaciones.equipo.1.docx)
@JohnFlorez25

**Comment by JohnFlorez25** [comment]
@juagui0105 perfecto, se aprueban las validaciones realizadas.
