### ISSUE TITLE
Realizar Historias de Usuario y criterios de aceptación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_sa_ppi2020#8]

**Comment by paulara04** [comment]
@JohnFlorez25 Ya estan montadas las historias de usuario y criterios de aceptación, para su revisión.

**Comment by JohnFlorez25** [comment]
@paulara04 agregar historias de usuario de acuerdo a las recomendaciones brindadas, es importante priorizar y tener en cuenta las funcionalidades claves de la aplicación de esta forma se abordan las acciones que va a ejecutar el usuario que va utilizar el sistema.

**Comment by JohnFlorez25** [comment]
Cumplen con las observaciones para la entrega de las historias de usuario
